export interface Ingredient {
  id: string;
  name: string;
  category: "protein" | "carb" | "fat";
  protein: number; // grams per 100g
  carbs: number; // grams per 100g
  fats: number; // grams per 100g
  calories: number; // calories per 100g
  emoji: string; // emoji representing the ingredient
  commonality?: number; // higher values = more common in households (0-100)
}

export const ingredients: Ingredient[] = [
  // Proteins
  {
    id: "chicken-breast",
    name: "Peito de Frango",
    category: "protein",
    protein: 31,
    carbs: 0,
    fats: 3.6,
    calories: 165,
    emoji: "🍗",
    commonality: 95,
  },
  {
    id: "beef",
    name: "Carne Bovina",
    category: "protein",
    protein: 26,
    carbs: 0,
    fats: 15,
    calories: 250,
    emoji: "🥩",
    commonality: 90,
  },
  {
    id: "eggs",
    name: "Ovos",
    category: "protein",
    protein: 13,
    carbs: 1.1,
    fats: 11,
    calories: 155,
    emoji: "🥚",
    commonality: 98,
  },
  {
    id: "tuna",
    name: "Atum",
    category: "protein",
    protein: 30,
    carbs: 0,
    fats: 1,
    calories: 130,
    emoji: "🐟",
    commonality: 65,
  },
  {
    id: "salmon",
    name: "Salmão",
    category: "protein",
    protein: 20,
    carbs: 0,
    fats: 13,
    calories: 208,
    emoji: "🐠",
    commonality: 50,
  },
  {
    id: "pork",
    name: "Carne Suína",
    category: "protein",
    protein: 27,
    carbs: 0,
    fats: 14,
    calories: 242,
    emoji: "🥓",
    commonality: 85,
  },
  {
    id: "cheese",
    name: "Queijo",
    category: "protein",
    protein: 25,
    carbs: 1.3,
    fats: 33,
    calories: 402,
    emoji: "🧀",
    commonality: 95,
  },
  {
    id: "yogurt",
    name: "Iogurte",
    category: "protein",
    protein: 10,
    carbs: 3.6,
    fats: 0.4,
    calories: 59,
    emoji: "🥛",
    commonality: 80,
  },
  {
    id: "tofu",
    name: "Tofu",
    category: "protein",
    protein: 8,
    carbs: 2,
    fats: 4,
    calories: 76,
    emoji: "🧊",
    commonality: 30,
  },
  {
    id: "beans",
    name: "Feijão",
    category: "protein",
    protein: 8.7,
    carbs: 19.9,
    fats: 0.5,
    calories: 127,
    emoji: "🫘",
    commonality: 99,
  },
  {
    id: "lentils",
    name: "Lentilha",
    category: "protein",
    protein: 9,
    carbs: 20,
    fats: 0.4,
    calories: 116,
    emoji: "🫛",
    commonality: 60,
  },
  {
    id: "chickpeas",
    name: "Grão de Bico",
    category: "protein",
    protein: 8.9,
    carbs: 27.4,
    fats: 2.6,
    calories: 164,
    emoji: "🌱",
    commonality: 55,
  },
  {
    id: "turkey",
    name: "Peru",
    category: "protein",
    protein: 29,
    carbs: 0,
    fats: 7,
    calories: 189,
    emoji: "🦃",
    commonality: 45,
  },
  {
    id: "cottage-cheese",
    name: "Queijo Cottage",
    category: "protein",
    protein: 11,
    carbs: 3.4,
    fats: 4.3,
    calories: 98,
    emoji: "🥫",
    commonality: 40,
  },
  {
    id: "whey-protein",
    name: "Whey Protein",
    category: "protein",
    protein: 80,
    carbs: 10,
    fats: 3,
    calories: 400,
    emoji: "💪",
    commonality: 60,
  },
  {
    id: "ground-beef",
    name: "Carne Moída",
    category: "protein",
    protein: 26,
    carbs: 0,
    fats: 15,
    calories: 250,
    emoji: "🥩",
    commonality: 92,
  },
  {
    id: "sardines",
    name: "Sardinha",
    category: "protein",
    protein: 25,
    carbs: 0,
    fats: 11,
    calories: 208,
    emoji: "🐟",
    commonality: 65,
  },
  {
    id: "mussarela",
    name: "Muçarela",
    category: "protein",
    protein: 22,
    carbs: 2,
    fats: 22,
    calories: 280,
    emoji: "🧀",
    commonality: 90,
  },

  // Carbs
  {
    id: "rice",
    name: "Arroz",
    category: "carb",
    protein: 2.7,
    carbs: 28,
    fats: 0.3,
    calories: 130,
    emoji: "🍚",
    commonality: 99,
  },
  {
    id: "pasta",
    name: "Macarrão",
    category: "carb",
    protein: 5.8,
    carbs: 30.9,
    fats: 0.9,
    calories: 158,
    emoji: "🍝",
    commonality: 96,
  },
  {
    id: "potato",
    name: "Batata",
    category: "carb",
    protein: 2,
    carbs: 17,
    fats: 0.1,
    calories: 77,
    emoji: "🥔",
    commonality: 95,
  },
  {
    id: "sweet-potato",
    name: "Batata Doce",
    category: "carb",
    protein: 1.6,
    carbs: 20,
    fats: 0.1,
    calories: 86,
    emoji: "🍠",
    commonality: 75,
  },
  {
    id: "bread",
    name: "Pão",
    category: "carb",
    protein: 9,
    carbs: 49,
    fats: 3.2,
    calories: 265,
    emoji: "🍞",
    commonality: 98,
  },
  {
    id: "oats",
    name: "Aveia",
    category: "carb",
    protein: 16.9,
    carbs: 66.3,
    fats: 6.9,
    calories: 389,
    emoji: "🌾",
    commonality: 70,
  },
  {
    id: "quinoa",
    name: "Quinoa",
    category: "carb",
    protein: 4.4,
    carbs: 21,
    fats: 1.9,
    calories: 120,
    emoji: "🌿",
    commonality: 40,
  },
  {
    id: "corn",
    name: "Milho",
    category: "carb",
    protein: 3.2,
    carbs: 19,
    fats: 1.5,
    calories: 106,
    emoji: "🌽",
    commonality: 85,
  },
  {
    id: "banana",
    name: "Banana",
    category: "carb",
    protein: 1.1,
    carbs: 22.8,
    fats: 0.3,
    calories: 89,
    emoji: "🍌",
    commonality: 96,
  },
  {
    id: "apple",
    name: "Maçã",
    category: "carb",
    protein: 0.3,
    carbs: 14,
    fats: 0.2,
    calories: 52,
    emoji: "🍎",
    commonality: 90,
  },
  {
    id: "broccoli",
    name: "Brócolis",
    category: "carb",
    protein: 2.8,
    carbs: 6.6,
    fats: 0.4,
    calories: 34,
    emoji: "🥦",
    commonality: 75,
  },
  {
    id: "spinach",
    name: "Espinafre",
    category: "carb",
    protein: 2.9,
    carbs: 3.6,
    fats: 0.4,
    calories: 23,
    emoji: "🍃",
    commonality: 65,
  },
  {
    id: "orange",
    name: "Laranja",
    category: "carb",
    protein: 0.9,
    carbs: 11.8,
    fats: 0.1,
    calories: 47,
    emoji: "🍊",
    commonality: 92,
  },
  {
    id: "strawberry",
    name: "Morango",
    category: "carb",
    protein: 0.7,
    carbs: 7.7,
    fats: 0.3,
    calories: 32,
    emoji: "🍓",
    commonality: 70,
  },
  {
    id: "blueberry",
    name: "Mirtilo",
    category: "carb",
    protein: 0.7,
    carbs: 14.5,
    fats: 0.3,
    calories: 57,
    emoji: "🫐",
    commonality: 40,
  },
  {
    id: "brown-rice",
    name: "Arroz Integral",
    category: "carb",
    protein: 2.6,
    carbs: 23,
    fats: 0.9,
    calories: 112,
    emoji: "🍚",
    commonality: 80,
  },
  {
    id: "yam",
    name: "Inhame",
    category: "carb",
    protein: 1.5,
    carbs: 27.9,
    fats: 0.1,
    calories: 118,
    emoji: "🍠",
    commonality: 60,
  },
  {
    id: "cassava",
    name: "Mandioca",
    category: "carb",
    protein: 1.4,
    carbs: 38,
    fats: 0.3,
    calories: 160,
    emoji: "🥔",
    commonality: 93,
  },
  {
    id: "french-bread",
    name: "Pão Francês",
    category: "carb",
    protein: 8,
    carbs: 57,
    fats: 2,
    calories: 289,
    emoji: "🥖",
    commonality: 97,
  },
  {
    id: "tomato",
    name: "Tomate",
    category: "carb",
    protein: 0.9,
    carbs: 3.9,
    fats: 0.2,
    calories: 18,
    emoji: "🍅",
    commonality: 95,
  },
  {
    id: "carrot",
    name: "Cenoura",
    category: "carb",
    protein: 0.9,
    carbs: 9.6,
    fats: 0.2,
    calories: 41,
    emoji: "🥕",
    commonality: 90,
  },
  {
    id: "flour",
    name: "Farinha de Trigo",
    category: "carb",
    protein: 10,
    carbs: 76,
    fats: 1,
    calories: 364,
    emoji: "🌾",
    commonality: 94,
  },
  {
    id: "sugar",
    name: "Açúcar",
    category: "carb",
    protein: 0,
    carbs: 100,
    fats: 0,
    calories: 387,
    emoji: "🧂",
    commonality: 98,
  },
  {
    id: "onion",
    name: "Cebola",
    category: "carb",
    protein: 1.1,
    carbs: 9.3,
    fats: 0.1,
    calories: 40,
    emoji: "🧅",
    commonality: 97,
  },
  {
    id: "garlic",
    name: "Alho",
    category: "carb",
    protein: 6.4,
    carbs: 33,
    fats: 0.5,
    calories: 149,
    emoji: "🧄",
    commonality: 96,
  },

  // Fats
  {
    id: "olive-oil",
    name: "Azeite",
    category: "fat",
    protein: 0,
    carbs: 0,
    fats: 100,
    calories: 884,
    emoji: "🫒",
    commonality: 92,
  },
  {
    id: "avocado",
    name: "Abacate",
    category: "fat",
    protein: 2,
    carbs: 8.5,
    fats: 15,
    calories: 160,
    emoji: "🥑",
    commonality: 75,
  },
  {
    id: "nuts",
    name: "Castanhas",
    category: "fat",
    protein: 15,
    carbs: 13.8,
    fats: 60.8,
    calories: 607,
    emoji: "🌰",
    commonality: 60,
  },
  {
    id: "butter",
    name: "Manteiga",
    category: "fat",
    protein: 0.9,
    carbs: 0.1,
    fats: 81.1,
    calories: 717,
    emoji: "🧈",
    commonality: 94,
  },
  {
    id: "coconut-oil",
    name: "Óleo de Coco",
    category: "fat",
    protein: 0,
    carbs: 0,
    fats: 99,
    calories: 862,
    emoji: "🥥",
    commonality: 50,
  },
  {
    id: "peanut-butter",
    name: "Pasta de Amendoim",
    category: "fat",
    protein: 25,
    carbs: 20,
    fats: 50,
    calories: 588,
    emoji: "🥜",
    commonality: 55,
  },
  {
    id: "almonds",
    name: "Amêndoas",
    category: "fat",
    protein: 21,
    carbs: 22,
    fats: 49,
    calories: 575,
    emoji: "🥜",
    commonality: 60,
  },
  {
    id: "walnuts",
    name: "Nozes",
    category: "fat",
    protein: 15,
    carbs: 14,
    fats: 65,
    calories: 654,
    emoji: "🌰",
    commonality: 40,
  },
  {
    id: "flaxseed",
    name: "Linhaça",
    category: "fat",
    protein: 18,
    carbs: 29,
    fats: 42,
    calories: 534,
    emoji: "🌱",
    commonality: 55,
  },
  {
    id: "chia-seeds",
    name: "Sementes de Chia",
    category: "fat",
    protein: 17,
    carbs: 42,
    fats: 31,
    calories: 486,
    emoji: "⚫",
    commonality: 50,
  },
  {
    id: "dark-chocolate",
    name: "Chocolate Amargo",
    category: "fat",
    protein: 7.8,
    carbs: 45.9,
    fats: 43.1,
    calories: 598,
    emoji: "🍫",
    commonality: 70,
  },
  {
    id: "coconut-milk",
    name: "Leite de Coco",
    category: "fat",
    protein: 2.3,
    carbs: 6.3,
    fats: 23.8,
    calories: 230,
    emoji: "🥥",
    commonality: 60,
  },
  {
    id: "cooking-oil",
    name: "Óleo de Cozinha",
    category: "fat",
    protein: 0,
    carbs: 0,
    fats: 100,
    calories: 884,
    emoji: "🧴",
    commonality: 99,
  },
  {
    id: "margarine",
    name: "Margarina",
    category: "fat",
    protein: 0.2,
    carbs: 0.7,
    fats: 80,
    calories: 717,
    emoji: "🧈",
    commonality: 88,
  },
  {
    id: "peanuts",
    name: "Amendoim",
    category: "fat",
    protein: 26,
    carbs: 16,
    fats: 49,
    calories: 567,
    emoji: "🥜",
    commonality: 75,
  },
  {
    id: "mayo",
    name: "Maionese",
    category: "fat",
    protein: 1,
    carbs: 8,
    fats: 75,
    calories: 680,
    emoji: "🧂",
    commonality: 88,
  },
  {
    id: "cream-cheese",
    name: "Cream Cheese",
    category: "fat",
    protein: 6,
    carbs: 4,
    fats: 34,
    calories: 342,
    emoji: "🧀",
    commonality: 80,
  },
  {
    id: "requeijao",
    name: "Requeijão",
    category: "fat",
    protein: 9,
    carbs: 3,
    fats: 28,
    calories: 290,
    emoji: "🧀",
    commonality: 92,
  },
];
